language: php
php:
- '7.3'

addons:
    sonarcloud:
        organization: 'adrien-chinour'
        token:
            secure: SONAR_TOKEN

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - composer test
    - sonar-scanner
