#!/usr/bin/env php
<?php

set_time_limit(0);

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('Todo Commands Application', '1.0');

// connection to database
try {
    $sqlite = __DIR__ . '/tasks.sqlite';
    $table = null;

    if (!file_exists($sqlite)) {
        $table = 'CREATE TABLE tasks(id INTEGER PRIMARY KEY NOT NULL, name TEXT, "group" TEXT, completed BOOLEAN)';
    }

    $pdo = new PDO('sqlite:tasks.sqlite');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    if ($table !== null) {
        $pdo->prepare($table)->execute();
    }
} catch (Exception $exception) {
    echo 'Could not connect to the database';
    exit(1);
}
$adapter = new \App\Database\DatabaseAdaptor($pdo);
$taskRepository = new \App\Database\TaskRepository($adapter);

// task CRUD commands
$application->add(new \App\Command\AddCommand($taskRepository));
$application->add(new \App\Command\ListCommand($taskRepository));
$application->add(new \App\Command\CheckCommand($taskRepository));
$application->add(new \App\Command\RemoveCommand($taskRepository));

$application->run();
