#!/usr/bin/env php
<?php

set_time_limit(0);

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('Todo Commands Application', '1.0');

// task CRUD commands
$application->add(new \App\Command\AddCommand());
$application->add(new \App\Command\ListCommand());
$application->add(new \App\Command\UpdateCommand());
$application->add(new \App\Command\RemoveCommand());

$application->run();
